kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: waf-operator-role-binding
  namespace: uwe-operator
subjects:
  - kind: ServiceAccount
    name: waf-operator
    namespace: uwe-operator    # should match quarkus.kubernetes.namespace in application.properties
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: waf-operator-role # should match metadata/name in waf-operator-role.yaml